using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace FGORandomizer.Migrations
{
    public partial class February2020 : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Servant",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    Name = table.Column<string>(nullable: true),
                    Class = table.Column<string>(nullable: true),
                    Rarity = table.Column<int>(nullable: false),
                    NA = table.Column<bool>(nullable: false),
                    Card = table.Column<string>(nullable: false),
                    Role = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Servant", x => x.Id);
                });

            migrationBuilder.InsertData(
                table: "Servant",
                columns: new[] { "Id", "Card", "Class", "NA", "Name", "Rarity", "Role" },
                values: new object[,]
                {
                    { 1, "A", "Shielder", true, "Mash Kyrielight", 4, "Support" },
                    { 155, "Q", "Berserker", true, "Mysterious Heroine X (Alter)", 5, "ST" },
                    { 156, "B", "Archer", true, "James Moriarty", 5, "ST" },
                    { 157, "A", "Caster", true, "EMIYA (Alter)", 4, "ST" },
                    { 158, "Q", "Avenger", true, "Hessian Lobo", 4, "ST" },
                    { 159, "Q", "Assassin", true, "Yan Qing", 4, "X" },
                    { 160, "B", "Saber", true, "Arthur Pendragon (Prototype)", 5, "AOE" },
                    { 161, "B", "Berserker", true, "Hijikata Toshizou", 5, "ST" },
                    { 162, "B", "Berserker", true, "Chacha", 4, "ST" },
                    { 163, "Q", "Alter Ego", true, "Meltryllis", 5, "ST" },
                    { 164, "B", "Alter Ego", true, "Passionlip", 4, "AOE" },
                    { 165, "B", "Saber", true, "Suzuka Gozen", 4, "AOE" },
                    { 166, "A", "Moon Cancer", true, "BB", 4, "ST" },
                    { 167, "A", "Alter Ego", true, "Kiara Sesshouin", 5, "AOE" },
                    { 169, "A", "Caster", false, "Scheherazade", 5, "AOE" },
                    { 170, "Q", "Assassin", false, "Wu Zetian", 4, "ST" },
                    { 171, "B", "Berserker", false, "Penthesilea", 4, "AOE" },
                    { 172, "B", "Rider", false, "Christopher Columbus", 3, "AOE" },
                    { 173, "A", "Ruler", false, "Sherlock Holmes", 5, "X" },
                    { 174, "B", "Berserker", false, "Paul Bunyan", 1, "AOE" },
                    { 175, "B", "Caster", false, "Nero Claudius (Caster)", 5, "AOE" },
                    { 176, "Q", "Saber", false, "Frankenstein (Saber)", 4, "ST" },
                    { 177, "A", "Assassin", false, "Nitocris (Assassin)", 4, "AOE" },
                    { 178, "B", "Berserker", false, "Oda Nobunaga (Berserker)", 4, "ST" },
                    { 179, "Q", "Rider", false, "Artoria Pendragon (Rider Alter)", 5, "ST" },
                    { 180, "A", "Archer", false, "Helena Blavatsky (Archer)", 4, "AOE" },
                    { 154, "B", "Caster", true, "King Hassan", 5, "ST" },
                    { 153, "B", "Saber", true, "Miyamoto Musashi", 5, "ST" },
                    { 150, "A", "Caster", true, "Merlin", 5, "AOE" },
                    { 148, "Q", "Lancer", true, "Jaguar Man", 3, "ST" },
                    { 122, "Q", "Archer", true, "Tristan", 4, "H" },
                    { 123, "B", "Saber", true, "Gawain", 4, "AOE" },
                    { 124, "A", "Assassin", true, "Hassan of Serenity", 3, "X" },
                    { 125, "B", "Archer", true, "Tawara Touta", 3, "AOE" },
                    { 126, "B", "Saber", true, "Bedivere", 3, "ST" },
                    { 127, "A", "Caster", true, "Leonardo Da Vinci", 5, "AOE" },
                    { 128, "B", "Lancer", true, "Tamamo no Mae (Lancer)", 5, "ST" },
                    { 129, "A", "Archer", true, "Artoria Pendragon (Archer)", 5, "ST" },
                    { 130, "A", "Caster", true, "Marie Antoinette (Caster)", 4, "H" },
                    { 131, "B", "Archer", true, "Anne Bonny & Mary Read (Archer)", 4, "ST" },
                    { 132, "A", "Rider", true, "Mordred (Rider)", 4, "AOE" },
                    { 133, "Q", "Assassin", true, "Scathach (Assassin)", 4, "AOE" },
                    { 181, "B", "Lancer", false, "Minamoto no Raikou (Lancer)", 4, "ST" },
                    { 134, "B", "Lancer", true, "Kiyohime (Lancer)", 4, "ST" },
                    { 136, "B", "Caster", true, "Illyasviel von Einzbern", 5, "ST" },
                    { 137, "A", "Archer", true, "Chloe von Einzbern", 4, "ST" },
                    { 138, "B", "Saber", true, "Elizabeth Bathory (Brave)", 4, "X" },
                    { 139, "B", "Assassin", true, "Cleopatra", 5, "AOE" },
                    { 140, "B", "Lancer", true, "Vlad III (EXTRA)", 4, "ST" },
                    { 141, "B", "Lancer", true, "Jeanne d'Arc Alter Santa Lily", 4, "H" },
                    { 142, "B", "Archer", true, "Ishtar", 5, "AOE" },
                    { 143, "B", "Lancer", true, "Enkidu", 5, "ST" },
                    { 144, "B", "Rider", true, "Quetzalcoatl", 5, "ST" },
                    { 145, "A", "Caster", true, "Gilgamesh (Caster)", 4, "H" },
                    { 146, "Q", "Lancer", true, "Medusa (Lancer)", 4, "ST" },
                    { 147, "B", "Avenger", true, "Gorgon", 4, "AOE" },
                    { 135, "B", "Ruler", true, "Martha (Ruler)", 4, "ST" },
                    { 182, "Q", "Rider", false, "Ishtar (Rider)", 4, "AOE" },
                    { 183, "Q", "Lancer", false, "Parvati", 4, "H" },
                    { 184, "B", "Archer", false, "Tomoe Gozen", 4, "ST" },
                    { 215, "Q", "Caster", false, "Scathach-Skadi", 5, "Support" },
                    { 216, "A", "Archer", false, "Jeanne d'Arc (Archer)", 5, "AOE" },
                    { 217, "B", "Lancer", false, "Ibaraki Douji (Lancer)", 4, "ST" },
                    { 218, "Q", "Assassin", false, "Ushiwakamaru (Assassin)", 4, "AOE" },
                    { 219, "B", "Berserker", false, "Jeanne d'Arc (Berserker Alter)", 4, "ST" },
                    { 220, "B", "Moon Cancer", false, "BB (Summer)", 5, "H" },
                    { 221, "A", "Saber", false, "Medb (Saber)", 4, "X" },
                    { 222, "A", "Foreigner", false, "Mysterious Heroine XX", 4, "ST" },
                    { 223, "Q", "Saber", false, "Diarmuid Ua Duibhne (Saber)", 4, "ST" },
                    { 224, "A", "Alter Ego", false, "Sitonai", 5, "ST" },
                    { 225, "B", "Caster", false, "Shuten Douji (Caster)", 4, "ST" },
                    { 226, "Q", "Berserker", false, "Xiang Yu", 5, "AOE" },
                    { 214, "Q", "Lancer", false, "Valkyrie", 4, "AOE" },
                    { 227, "A", "Saber", false, "Lanling Wang", 4, "X" },
                    { 229, "A", "Ruler", false, "Shi Huang Di", 5, "Support" },
                    { 230, "B", "Assassin", false, "Yu Miaoyi", 4, "AOE" },
                    { 231, "Q", "Rider", false, "Red Hare", 3, "AOE" },
                    { 232, "Q", "Lancer", false, "Bradamante", 5, "AOE" },
                    { 233, "B", "Ruler", false, "Quetzalcoatl (Samba/Santa)", 4, "AOE" },
                    { 234, "A", "Saber", false, "Beni-enma", 5, "H" },
                    { 235, "A", "Assassin", false, "Li Shuwen (Assassin)", 5, "ST" },
                    { 236, "A", "Caster", false, "Miyu Edelfelt", 4, "Support" },
                    { 237, "A", "Caster", false, "Murasaki Shikibu", 5, "AOE" },
                    { 238, "B", "Alter Ego", false, "Kingprotea", 5, "AOE" },
                    { 239, "Q", "Assassin", false, "Kama", 5, "ST" },
                    { 241, "A", "Rider", false, "Sima Yi (Reines)", 5, "Support" },
                    { 228, "A", "Lancer", false, "Qin Liangyu", 4, "X" },
                    { 121, "A", "Saber", true, "Lancelot (Saber)", 4, "ST" },
                    { 213, "B", "Saber", false, "Sigurd", 5, "ST" },
                    { 211, "A", "Rider", false, "Sakamoto Ryouma", 4, "ST" },
                    { 185, "A", "Assassin", false, "Mochizuki Chiyome", 4, "X" },
                    { 186, "Q", "Lancer", false, "Houzouin Inshun", 3, "ST" },
                    { 187, "A", "Saber", false, "Yagyu Munenori", 4, "ST" },
                    { 188, "B", "Assassin", false, "Katou Danzou", 4, "H" },
                    { 189, "Q", "Assassin", false, "Osakabehime", 5, "Support" },
                    { 190, "B", "Alter Ego", false, "Mecha Eli-chan", 4, "ST" },
                    { 191, "B", "Alter Ego", false, "Mecha Eli-chan Mk.II", 4, "ST" },
                    { 192, "B", "Caster", false, "Circe", 4, "H" },
                    { 193, "B", "Lancer", false, "Nezha", 4, "AOE" },
                    { 194, "A", "Caster", false, "Queen of Sheba", 4, "ST" },
                    { 195, "A", "Foreigner", false, "Abigail Williams", 5, "X" },
                    { 196, "B", "Lancer", false, "Ereshkigal", 5, "H" },
                    { 212, "B", "Archer", false, "Napolean", 5, "AOE" },
                    { 197, "Q", "Archer", false, "Attila the San(ta)", 4, "ST" },
                    { 199, "B", "Assassin", false, "Semiramis", 5, "AOE" },
                    { 200, "B", "Archer", false, "Asagami Fujino", 4, "AOE" },
                    { 201, "A", "Caster", false, "Anastasia Nikolaevna Romanova", 5, "AOE" },
                    { 202, "Q", "Berserker", false, "Atalanta (Alter)", 4, "ST" },
                    { 203, "A", "Caster", false, "Avicebron", 3, "H" },
                    { 204, "A", "Avenger", false, "Antonia Salieri", 3, "AOE" },
                    { 205, "B", "Rider", false, "Ivan the Terrible", 5, "AOE" },
                    { 206, "Q", "Rider", false, "Achilles", 5, "AOE" },
                    { 207, "A", "Archer", false, "Chiron", 4, "H" },
                    { 208, "A", "Caster", false, "Sieg", 4, "AOE" },
                    { 209, "B", "Alter Ego", false, "Okita Souji (Alter)", 5, "AOE" },
                    { 210, "Q", "Assassin", false, "Okada Izou", 3, "ST" },
                    { 198, "A", "Foreigner", false, "Katsushika Hokusai", 5, "AOE" },
                    { 242, "A", "Ruler", false, "Astraea", 4, "ST" },
                    { 120, "A", "Caster", true, "Nitocris", 4, "AOE" },
                    { 118, "B", "Rider", true, "Ozymandias", 5, "H" },
                    { 32, "A", "Caster", true, "Gilles de Rais (Caster)", 3, "X" },
                    { 33, "A", "Caster", true, "Hans Christian Andersen", 2, "Support" },
                    { 34, "B", "Caster", true, "William Shakespeare", 2, "Support" },
                    { 35, "A", "Caster", true, "Mephistopheles", 3, "X" },
                    { 36, "A", "Caster", true, "Wolfgang Amadeus Mozart", 1, "Support" },
                    { 37, "A", "Caster", true, "Zhuge Liang (Lord El-Melloi II)", 5, "Support" },
                    { 38, "B", "Caster", true, "Cu Chulainn (Caster)", 3, "AOE" },
                    { 39, "Q", "Assassin", true, "Sasaki Kojiro", 1, "ST" },
                    { 40, "Q", "Assassin", true, "Hassan of the Cursed Arm", 2, "H" },
                    { 41, "Q", "Assassin", true, "Stheno", 4, "X" },
                    { 42, "Q", "Assassin", true, "Jing Ke", 3, "ST" },
                    { 43, "B", "Assassin", true, "Charles-Henri Sanson", 2, "ST" },
                    { 44, "A", "Assassin", true, "Phantom of the Opera", 2, "X" },
                    { 45, "Q", "Assassin", true, "Mata Hari", 1, "X" },
                    { 46, "B", "Assassin", true, "Carmilla", 4, "ST" },
                    { 47, "B", "Berserker", true, "Heracles", 4, "ST" },
                    { 48, "Q", "Berserker", true, "Lancelot", 4, "AOE" },
                    { 49, "B", "Berserker", true, "Lu Bu Fengxian", 3, "ST" },
                    { 50, "B", "Berserker", true, "Spartacus", 1, "AOE" },
                    { 51, "B", "Berserker", true, "Sakata Kintoki", 5, "ST" },
                    { 52, "A", "Berserker", true, "Vlad III", 5, "ST" },
                    { 53, "A", "Berserker", true, "Asterios", 1, "X" },
                    { 54, "B", "Berserker", true, "Caligula", 2, "AOE" },
                    { 55, "B", "Berserker", true, "Darius III", 3, "AOE" },
                    { 56, "B", "Berserker", true, "Kiyohime", 3, "AOE" },
                    { 31, "A", "Caster", true, "Medusa", 3, "ST" },
                    { 30, "B", "Rider", true, "Martha", 4, "H" },
                    { 29, "Q", "Rider", true, "Marie Antoinette", 4, "H" },
                    { 28, "Q", "Rider", true, "Alexander", 3, "H" },
                    { 2, "B", "Saber", true, "Artoria Pendragon", 5, "AOE" },
                    { 3, "B", "Saber", true, "Artoria Pendragon (Alter)", 4, "AOE" },
                    { 4, "B", "Saber", true, "Artoria Pendragon (Lily)", 4, "AOE" },
                    { 5, "A", "Saber", true, "Nero Claudius", 4, "AOE" },
                    { 6, "B", "Saber", true, "Siegfried", 4, "AOE" },
                    { 7, "Q", "Saber", true, "Gaius Julius Caesar", 3, "H" },
                    { 8, "B", "Saber", true, "Altera", 5, "AOE" },
                    { 9, "A", "Saber", true, "Gilles de Rais (Saber)", 3, "X" },
                    { 10, "A", "Saber", true, "Chevalier d'Eon", 4, "Support" },
                    { 11, "B", "Archer", true, "EMIYA", 4, "AOE" },
                    { 12, "B", "Archer", true, "Gilgamesh", 5, "AOE" },
                    { 13, "A", "Archer", true, "Robin Hood", 3, "ST" },
                    { 57, "B", "Berserker", true, "Eric Bloodaxe", 2, "AOE" },
                    { 14, "Q", "Archer", true, "Atalanta", 4, "AOE" },
                    { 16, "B", "Archer", true, "Arash", 1, "AOE" },
                    { 17, "Q", "Lancer", true, "Cu Chulainn", 3, "ST" },
                    { 18, "B", "Lancer", true, "Elizabeth Bathory", 4, "AOE" },
                    { 19, "A", "Lancer", true, "Musashibo Benkei", 2, "X" },
                    { 20, "Q", "Lancer", true, "Cu Chulainn (Prototype)", 3, "ST" },
                    { 21, "B", "Lancer", true, "Leonidas I", 2, "Support" },
                    { 22, "B", "Lancer", true, "Romulus", 3, "AOE" },
                    { 23, "Q", "Rider", true, "Medusa", 3, "AOE" },
                    { 24, "A", "Rider", true, "Georgios", 2, "Support" },
                    { 25, "B", "Rider", true, "Edward Teach", 2, "H" },
                    { 26, "A", "Rider", true, "Boudica", 3, "Support" },
                    { 27, "Q", "Rider", true, "Ushiwakamaru", 3, "ST" },
                    { 15, "A", "Archer", true, "Euryale", 3, "ST" },
                    { 58, "B", "Berserker", true, "Tamamo Cat", 4, "AOE" },
                    { 59, "A", "Ruler", true, "Jeanne d'Arc", 5, "Support" },
                    { 60, "A", "Archer", true, "Orion", 5, "ST" },
                    { 92, "A", "Assassin", true, "Ryougi Shiki (Assassin)", 4, "ST" },
                    { 93, "B", "Ruler", true, "Amakusa Shirou", 5, "H" },
                    { 94, "Q", "Rider", true, "Astolfo", 3, "AOE" },
                    { 95, "B", "Archer", true, "Gilgamesh (Child)", 3, "AOE" },
                    { 96, "Q", "Avenger", true, "Edmond Dantès", 5, "AOE" },
                    { 97, "B", "Berserker", true, "Nightingale", 5, "Support" },
                    { 98, "B", "Berserker", true, "Cu Chulainn (Alter)", 5, "ST" },
                    { 99, "B", "Rider", true, "Medb", 5, "ST" },
                    { 100, "A", "Caster", true, "Helena Blavatsky", 4, "H" },
                    { 101, "B", "Saber", true, "Rama", 4, "ST" },
                    { 102, "A", "Lancer", true, "Li Shuwen (Lancer)", 4, "ST" },
                    { 103, "A", "Caster", true, "Thomas Edison", 4, "X" },
                    { 91, "A", "Saber", true, "Ryougi Shiki (Saber)", 5, "AOE" },
                    { 104, "A", "Caster", true, "Geronimo", 3, "H" },
                    { 106, "B", "Avenger", true, "Jeanne d'Arc (Alter)", 5, "ST" },
                    { 107, "Q", "Avenger", true, "Angra Mainyu", 2, "X" },
                    { 108, "B", "Rider", true, "Iskandar", 5, "AOE" },
                    { 109, "A", "Assassin", true, "EMIYA (Assassin)", 4, "ST" },
                    { 110, "A", "Assassin", true, "Hundred Face Hassan", 3, "ST" },
                    { 111, "A", "Caster", true, "Irisviel (Dress of Heaven)", 4, "Support" },
                    { 112, "A", "Assassin", true, "Shuten Douji", 5, "AOE" },
                    { 113, "B", "Caster", true, "Xuanzang Sanzang", 5, "ST" },
                    { 114, "B", "Berserker", true, "Minamoto no Raikou", 5, "AOE" },
                    { 115, "Q", "Rider", true, "Sakata Kintoki (Rider)", 4, "ST" },
                    { 116, "B", "Berserker", true, "Ibaraki Douji", 4, "ST" },
                    { 117, "Q", "Assassin", true, "Fuma Kotarou", 3, "X" },
                    { 105, "Q", "Archer", true, "Billy the Kid", 3, "ST" },
                    { 119, "B", "Lancer", true, "Artoria Pendragon (Lancer)", 5, "AOE" },
                    { 90, "A", "Saber", true, "Nero Claudius (Bride)", 5, "H" },
                    { 88, "B", "Lancer", true, "Brynhildr", 5, "ST" },
                    { 61, "B", "Caster", true, "Elizabeth Bathory (Halloween)", 4, "AOE" },
                    { 62, "A", "Caster", true, "Tamamo no Mae", 5, "Support" },
                    { 63, "A", "Archer", true, "David", 3, "Support" },
                    { 64, "B", "Lancer", true, "Hector", 3, "H" },
                    { 65, "B", "Rider", true, "Francis Drake", 5, "AOE" },
                    { 66, "Q", "Rider", true, "Anne Bonny & Mary Read", 4, "ST" },
                    { 67, "A", "Caster", true, "Medea (Lily)", 4, "Support" },
                    { 68, "Q", "Saber", true, "Okita Souji", 5, "ST" },
                    { 69, "B", "Archer", true, "Oda Nobunaga", 4, "AOE" },
                    { 70, "Q", "Lancer", true, "Scathach", 5, "ST" },
                    { 71, "Q", "Lancer", true, "Diarmuid Ua Duibhne", 3, "ST" },
                    { 72, "B", "Saber", true, "Fergus mac Roich", 3, "AOE" },
                    { 89, "B", "Berserker", true, "Beowulf", 4, "ST" },
                    { 73, "B", "Rider", true, "Artoria Pendragon (Santa Alter)", 4, "AOE" },
                    { 75, "Q", "Assassin", true, "Jack the Ripper", 5, "ST" },
                    { 76, "B", "Saber", true, "Mordred", 5, "AOE" },
                    { 77, "B", "Archer", true, "Nikola Tesla", 5, "AOE" },
                    { 78, "B", "Lancer", true, "Artoria Pendragon (Lancer Alter)", 4, "AOE" },
                    { 79, "A", "Caster", true, "Paracelsus von Hohenheim", 3, "Support" },
                    { 80, "B", "Caster", true, "Charles Babbage", 3, "AOE" },
                    { 81, "B", "Assassin", true, "Henry Jekyll & Hyde", 3, "X" },
                    { 82, "Q", "Berserker", true, "Frankenstein", 4, "AOE" },
                    { 84, "B", "Archer", true, "Arjuna", 5, "AOE" },
                    { 85, "B", "Lancer", true, "Karna", 5, "AOE" },
                    { 86, "Q", "Assassin", true, "Mysterious Heroine X", 5, "ST" },
                    { 87, "A", "Lancer", true, "Fionn mac Cumhaill", 4, "AOE" },
                    { 74, "A", "Caster", true, "Nursery Rhyme", 4, "AOE" },
                    { 243, "B", "Assassin", false, "Gray", 4, "AOE" }
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Servant");
        }
    }
}
